import Foundation

public enum PianobarCore {
    public static let version = "0.1.0"
}

/// Exposes package-bundle resources to dependent targets. `Bundle.module`
/// is generated by SwiftPM but is internal to the package; this helper
/// re-exports what the app target needs.
public enum PianobarCoreResources {
    public static var eventBridgeScriptURL: URL {
        guard let url = Bundle.module.url(
            forResource: "event_bridge", withExtension: "sh")
        else {
            fatalError("event_bridge.sh missing from PianobarCore resources")
        }
        return url
    }
}
